// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: proto/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface GetProductIDReq {
  productId: number;
}

export interface ProductRes {
  productId: number;
  name: string;
  description: string;
  price: number;
  stock: number;
  categoryId: number;
}

export interface CreateProductReq {
  name: string;
  description: string;
  price: number;
  stock: number;
  categoryId: number;
}

export interface UpdateProductReq {
  productId: number;
  name?: string | undefined;
  description?: string | undefined;
  price?: number | undefined;
  stock?: number | undefined;
  categoryId?: number | undefined;
}

export interface DeleteProductRes {
  success: boolean;
  message: string;
}

export interface ProductByCategoryReq {
  categoryId: number;
}

export interface ProductListRes {
  products: ProductRes[];
}

export const PRODUCTS_PACKAGE_NAME = "products";

export interface ProductServiceClient {
  getProduct(request: GetProductIDReq): Observable<ProductRes>;

  getProductsByCategory(request: ProductByCategoryReq): Observable<ProductListRes>;

  createProduct(request: CreateProductReq): Observable<ProductRes>;

  updateProduct(request: UpdateProductReq): Observable<ProductRes>;

  deleteProduct(request: GetProductIDReq): Observable<DeleteProductRes>;
}

export interface ProductServiceController {
  getProduct(request: GetProductIDReq): Promise<ProductRes> | Observable<ProductRes> | ProductRes;

  getProductsByCategory(
    request: ProductByCategoryReq,
  ): Promise<ProductListRes> | Observable<ProductListRes> | ProductListRes;

  createProduct(request: CreateProductReq): Promise<ProductRes> | Observable<ProductRes> | ProductRes;

  updateProduct(request: UpdateProductReq): Promise<ProductRes> | Observable<ProductRes> | ProductRes;

  deleteProduct(request: GetProductIDReq): Promise<DeleteProductRes> | Observable<DeleteProductRes> | DeleteProductRes;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getProduct",
      "getProductsByCategory",
      "createProduct",
      "updateProduct",
      "deleteProduct",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
