// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: proto/products_order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "products_order";

export interface ProductOrderRequest {
  productId: number;
  quantity: number;
}

export interface ProductAvailabilityResponse {
  available: boolean;
}

export interface OrderCompletedResponse {
}

export const PRODUCTS_ORDER_PACKAGE_NAME = "products_order";

export interface ProductsOrderServiceClient {
  checkProductAvailability(request: ProductOrderRequest): Observable<ProductAvailabilityResponse>;

  orderCompleted(request: ProductOrderRequest): Observable<OrderCompletedResponse>;
}

export interface ProductsOrderServiceController {
  checkProductAvailability(
    request: ProductOrderRequest,
  ): Promise<ProductAvailabilityResponse> | Observable<ProductAvailabilityResponse> | ProductAvailabilityResponse;

  orderCompleted(
    request: ProductOrderRequest,
  ): Promise<OrderCompletedResponse> | Observable<OrderCompletedResponse> | OrderCompletedResponse;
}

export function ProductsOrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkProductAvailability", "orderCompleted"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductsOrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductsOrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_ORDER_SERVICE_NAME = "ProductsOrderService";
