// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: proto/categories.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "categories";

export interface GetCategoryIDReq {
  categoryId: number;
}

/** Empty request for getting all categories */
export interface GetCategoriesReq {
}

export interface CategoryRes {
  categoryId: number;
  name: string;
}

export interface CategoryListRes {
  categories: CategoryRes[];
}

export interface CreateCategoryReq {
  name: string;
}

export interface UpdateCategoryReq {
  categoryId: number;
  name?: string | undefined;
}

export interface DeleteCategoryRes {
  success: boolean;
  message: string;
}

export const CATEGORIES_PACKAGE_NAME = "categories";

export interface CategoryServiceClient {
  getCategory(request: GetCategoryIDReq): Observable<CategoryRes>;

  getCategories(request: GetCategoriesReq): Observable<CategoryListRes>;

  createCategory(request: CreateCategoryReq): Observable<CategoryRes>;

  updateCategory(request: UpdateCategoryReq): Observable<CategoryRes>;

  deleteCategory(request: GetCategoryIDReq): Observable<DeleteCategoryRes>;
}

export interface CategoryServiceController {
  getCategory(request: GetCategoryIDReq): Promise<CategoryRes> | Observable<CategoryRes> | CategoryRes;

  getCategories(request: GetCategoriesReq): Promise<CategoryListRes> | Observable<CategoryListRes> | CategoryListRes;

  createCategory(request: CreateCategoryReq): Promise<CategoryRes> | Observable<CategoryRes> | CategoryRes;

  updateCategory(request: UpdateCategoryReq): Promise<CategoryRes> | Observable<CategoryRes> | CategoryRes;

  deleteCategory(
    request: GetCategoryIDReq,
  ): Promise<DeleteCategoryRes> | Observable<DeleteCategoryRes> | DeleteCategoryRes;
}

export function CategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "getCategories",
      "createCategory",
      "updateCategory",
      "deleteCategory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CATEGORY_SERVICE_NAME = "CategoryService";
