// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: proto/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface ProductReq {
  productId: number;
}

export interface ProductRes {
  productId: number;
  name: string;
  description: string;
  price: number;
  stock: number;
  categoryId: number;
}

export interface ProductByCategoryReq {
  categoryId: number;
}

export interface ProductListRes {
  products: ProductRes[];
}

export const PRODUCTS_PACKAGE_NAME = "products";

export interface ProductServiceClient {
  getProduct(request: ProductReq): Observable<ProductRes>;

  getProductsByCategory(request: ProductByCategoryReq): Observable<ProductListRes>;
}

export interface ProductServiceController {
  getProduct(request: ProductReq): Promise<ProductRes> | Observable<ProductRes> | ProductRes;

  getProductsByCategory(
    request: ProductByCategoryReq,
  ): Promise<ProductListRes> | Observable<ProductListRes> | ProductListRes;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProduct", "getProductsByCategory"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
